# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sdpctl < Formula
  desc "Official CLI tool for managing AppGate SDP Collectives"
  homepage "https://appgate.github.io/sdpctl/"
  version "2026.06.08"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/appgate/sdpctl/releases/download/2026.06.08/sdpctl_2026.06.08_darwin_arm64.tar.gz"
      sha256 "027ad4cbd1768685eeb00b2d31f56dddc952b4dbba435020901a4ed47588fcb3"

      def install
        bin.install "sdpctl"
        generate_completions_from_executable("#{bin}/sdpctl", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/appgate/sdpctl/releases/download/2026.06.08/sdpctl_2026.06.08_darwin_amd64.tar.gz"
      sha256 "60f8a3ab0efe4bd3538ee42312f47d5899828fbf89f2916f289b4d4157e054ec"

      def install
        bin.install "sdpctl"
        generate_completions_from_executable("#{bin}/sdpctl", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/appgate/sdpctl/releases/download/2026.06.08/sdpctl_2026.06.08_linux_arm64.tar.gz"
      sha256 "3f06e6d5184486d6e84c2693de823c8ae21557c3ecb1fb54bf25b85af173d06f"

      def install
        bin.install "sdpctl"
        generate_completions_from_executable("#{bin}/sdpctl", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/appgate/sdpctl/releases/download/2026.06.08/sdpctl_2026.06.08_linux_amd64.tar.gz"
      sha256 "0be408b45777bcdfc8ffd15a0a5b100267d4a245dd2f7a8a9b51294b466da2bf"

      def install
        bin.install "sdpctl"
        generate_completions_from_executable("#{bin}/sdpctl", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  test do
    version_output = shell_output("#{bin}/sdpctl --version")
    assert_match "sdpctl version #{version}", version_output.split("\n")[0]

    profile_add = shell_output("#{bin}/sdpctl profile add test")
    expected = "Created profile test, run 'sdpctl profile list' to see all available profiles\n" \
               "run 'sdpctl profile set test' to select the new profile"
    assert_match expected, profile_add

    profile_set = shell_output("#{bin}/sdpctl profile set test")
    expected = "test is selected as current sdp profile\n" \
               "test is not configured yet, run 'sdpctl configure'"
    assert_match expected, profile_set

    configure = shell_output("#{bin}/sdpctl configure https://example.com:8443")
    expected = "Configuration updated successfully"
    assert_match expected, configure
  end
end
