name: Auto-Merge

on:
  repository_dispatch:
    types: [sdpctl_release]

jobs:
  automerge:
    name: Automerge Tap
    runs-on: ubuntu-latest
    steps:
      - name: Find
        uses: juliangruber/find-pull-request-action@v1
        id: find-pull-request
        with:
          branch: sdpctl-${{ github.event.client_payload.version }}
      - name: Approve
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.find-pull-request.outputs.number }}
      - name: Merge
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.find-pull-request.outputs.number }}
          method: merge

